# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Messages

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HealthMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HealthMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHealthMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HealthMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HealthMessage
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HealthMessage
    def Contents(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Messages.HealthContents import HealthContents
            obj = HealthContents()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def HealthMessageStart(builder):
    builder.StartObject(2)

def Start(builder):
    HealthMessageStart(builder)

def HealthMessageAddType(builder, type):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(type), 0)

def AddType(builder, type):
    HealthMessageAddType(builder, type)

def HealthMessageAddContents(builder, contents):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(contents), 0)

def AddContents(builder, contents):
    HealthMessageAddContents(builder, contents)

def HealthMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return HealthMessageEnd(builder)
