# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14health_service.proto\"(\n\rHealthRequest\x12\x17\n\x0frequest_content\x18\x01 \x01(\t\"/\n\x0eHealthResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2?\n\rHealthService\x12.\n\x0b\x43heckHealth\x12\x0e.HealthRequest\x1a\x0f.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEALTHREQUEST']._serialized_start=24
  _globals['_HEALTHREQUEST']._serialized_end=64
  _globals['_HEALTHRESPONSE']._serialized_start=66
  _globals['_HEALTHRESPONSE']._serialized_end=113
  _globals['_HEALTHSERVICE']._serialized_start=115
  _globals['_HEALTHSERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
