# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: health_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14health_service.proto\x12\x06health\"!\n\rHealthRequest\x12\x10\n\x08\x63ontents\x18\x01 \x01(\t\"!\n\x0eHealthResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2M\n\rHealthService\x12<\n\x0b\x43heckHealth\x12\x15.health.HealthRequest\x1a\x16.health.HealthResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEALTHREQUEST._serialized_start=32
  _HEALTHREQUEST._serialized_end=65
  _HEALTHRESPONSE._serialized_start=67
  _HEALTHRESPONSE._serialized_end=100
  _HEALTHSERVICE._serialized_start=102
  _HEALTHSERVICE._serialized_end=179
# @@protoc_insertion_point(module_scope)
