# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Messages

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Bottles(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # Bottles
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bottles
    def Sprite(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateBottles(builder, sprite):
    builder.Prep(4, 4)
    builder.PrependInt32(sprite)
    return builder.Offset()
